export enum MapGetters {
    boxAccessToken = 'map/boxAccessToken',
    compareBarPosition = 'map/compareBarPosition',
    googleMapsApiKey = 'map/googleMapsApiKey',
    map = 'map/map',
    mapTooltip = 'map/mapTooltip',
    mapTooltipMessage = 'map/mapTooltipMessage',
    initialZoom = 'map/initialZoom',
    center = 'map/center',
    isMapConf = 'map/isMapConf',
    activeLayerTileId = 'map/activeLayerTileId',
    layers = 'map/layers',
    boudningLayers = 'map/boudningLayers',
    customLayers = 'map/customLayers',
    hoveredLayerId = 'map/hoveredLayerId',
    clickedLayerId = 'map/clickedLayerId',
    shareParams = 'map/shareParams',
    activeLayerLegend = 'map/activeLayerLegend',
    supportedLegendTypes = 'map/supportedLegendTypes',
    showFull = 'map/showFull',
    hideSearching = 'map/hideSearching',
    hideSeeAlso = 'map/hideSeeAlso',
    compareLayer = 'map/compareLayer',
    progressBarLoading = 'map/progressBarLoading',
    progressBarLoaded = 'map/progressBarLoaded',
    progressBarPercentage = 'map/progressBarPercentage',
    progressBarEnable = 'map/progressBarEnable'
}
