export const servicesTest = `
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2005/Atom http://essi-lab.eu/schemas/geo-rss/atom_1.0_specification.xsd http://www.georss.org/georss http://essi-lab.eu/schemas/geo-rss/geo_rss_1.1_specification.xsd http://www.opengis.net/gml http://schemas.opengis.net/gml/3.1.1/base/gml.xsd">
	<title>Search results</title>
	<id>ac56fa10-fadc-4fc7-b3cc-8e101888a05a</id>
	<link href="http://production.geodab.eu:-1/gi-cat-StP/services/opensearch?getdescriptiondocument" rel="search" title="Content Search" type="application/opensearchdescription+xml"/>
	<totalResults xmlns="http://a9.com/-/spec/opensearch/1.1/">1</totalResults>
	<startIndex xmlns="http://a9.com/-/spec/opensearch/1.1/">1</startIndex>
	<itemsPerPage xmlns="http://a9.com/-/spec/opensearch/1.1/">12</itemsPerPage>
	<entry>
		<title>Land cover change</title>
		<atom:logo xmlns:atom="http://www.w3.org/2005/Atom">https://previews.123rf.com/images/shottythefirst/shottythefirst1403/shottythefirst140300017/26763546-simple-yellow-orange-fractal-wall-crack-background-square-dimensions.jpg</atom:logo>
		<id>671c5ddf-a8df-4afe-a7d0-d8b3b840d64c</id>
		<content>image/gif image/png image/png; mode=24bit image/jpeg image/wbmp image/tiff image/svg+xml</content>
		<summary>Etiam imperdiet imperdiet orci. Sed cursus turpis vitae tortor. Curabitur suscipit suscipit tellus.Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vulputate eleifend tellus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</summary>
		<category label="service_resource" term="geoss_cr_type"/>
		<contributor>
			<orgName>European Commision</orgName>
			<indName/>
			<email/>
			<role/>
		</contributor>
		<box xmlns="http://www.georss.org/georss">tbfilled</box>
		<gmd:distributionInfo xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gvq="http://www.geoviqua.org/QualityInformationModel/4.0" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gml="http://www.opengis.net/gml" xmlns:dm="http://floraresearch.eu/sdi/services/7.0/dataModel/schema" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows" xmlns:ns4="http://quakeml.org/xmlns/bed/1.2" xmlns:wstxns1="http://floraresearch.eu/sdi/services/7.0/dataModel/schema" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:dct="http://purl.org/dc/terms/" xmlns:rim="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:wrs="http://www.opengis.net/cat/wrs/1.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xlink="http://www.w3.org/1999/xlink">
			<gmd:MD_Distribution>
				<gmd:transferOptions>
					<gmd:MD_DigitalTransferOptions>
						<gmd:onLine>
							<gmd:CI_OnlineResource>
								<gmd:linkage><!--from service resource -> transferoption -> endpoint.url-->
									<gmd:URL>https://pqqsdba4n9.execute-api.us-east-1.amazonaws.com/alpha/workflows</gmd:URL>
								</gmd:linkage>
								<gmd:protocol> <!-- from service resources -> transferoption.protocol-->
									<gco:CharacterString>ecopotential_workflow_api</gco:CharacterString>
								</gmd:protocol>
								<gmd:name><!--from service transferoption.name-->
									<gco:CharacterString>http://eu.floraresearch.essi.core/workflow/autogenerated-1527585007813-process</gco:CharacterString>
								</gmd:name>
								<gmd:description>
									<gco:CharacterString>land cover change calculation</gco:CharacterString>
									<gmx:Anchor xlink:href="http://www.geoportal.org/resourcetypes/service_resource" />
								</gmd:description>
							</gmd:CI_OnlineResource>
						</gmd:onLine>
					</gmd:MD_DigitalTransferOptions>
				</gmd:transferOptions>
			</gmd:MD_Distribution>
		</gmd:distributionInfo>
	</entry>
</feed>`
