import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer/Footer";
import NavHeader from "./components/Nav/NavHeader";

export const metadata: Metadata = {
  title: "Geoss landing page",
  description: "Generated by create next app",
};

export const revalidate = 60


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const portalUrl = process.env.NEXT_PUBLIC_PORTAL_URL
  return (
    <html lang="en">
      <body className="scrollbar font-esa">
        <NavHeader portalUrl={portalUrl}/>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
