export enum GeneralFiltersActions {
    setSources = 'generalFilters/setSources',
    setViewId = 'generalFilters/setViewId',
    setLocationType = 'generalFilters/setLocationType',
    setLocationTypeOptions = 'generalFilters/setLocationTypeOptions',
    setGooglePlacesInput = 'generalFilters/setGooglePlacesInput',
    setSelectedAreaCoordinates = 'generalFilters/setSelectedAreaCoordinates',
    setBoundingBoxRelation = 'generalFilters/setBoundingBoxRelation',
    setSearchFields = 'generalFilters/setSearchFields',
    setAdditionalSearchFields = 'generalFilters/setAdditionalSearchFields',
    setPhrase = 'generalFilters/setPhrase',
    setTermFrequency = 'generalFilters/setTermFrequency',
    setResultsPerPage = 'generalFilters/setResultsPerPage',
    setRequestId = 'generalFilters/setRequestId',
    setDateFrom = 'generalFilters/setDateFrom',
    setDateTo = 'generalFilters/setDateTo',
    setDatePeriod = 'generalFilters/setDatePeriod',
    setContainerVisible = 'generalFilters/setContainerVisible',
    setGeossDataCore = 'generalFilters/setGeossDataCore',
    reset = 'generalFilters/reset',
    setLastTriggerredState = 'generalFilters/setLastTriggerredState',
    setInChangeProcess = 'generalFilters/setInChangeProcess',
    parseValues = 'generalFilters/parseValues',
    setWorkflowMapDraw = 'generalFilters/setWorkflowMapDraw',
    setGooglePlacesApiError = 'generalFilters/setGooglePlacesApiError'
}
