FROM node:16.19.0-alpine

COPY . .

RUN yarn --non-interactive install 
RUN echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

EXPOSE 3000

CMD ["yarn", "--non-interactive", "run", "dev"]