export enum FacetedFiltersActions {
    setKeyword = 'facetedFilters/setKeyword',
    setKeywordOptions = 'facetedFilters/setKeywordOptions',
    setFormat = 'facetedFilters/setFormat',
    setFormatOptions = 'facetedFilters/setFormatOptions',
    setSource = 'facetedFilters/setSource',
    setSourceOptions = 'facetedFilters/setSourceOptions',
    setProtocol = 'facetedFilters/setProtocol',
    setProtocolOptions = 'facetedFilters/setProtocolOptions',
    setOrganisation = 'facetedFilters/setOrganisation',
    setOrganisationOptions = 'facetedFilters/setOrganisationOptions',
    setScore = 'facetedFilters/setScore',
    setScoreOptions = 'facetedFilters/setScoreOptions',
    setFacetedFiltersAvailable = 'facetedFilters/setFacetedFiltersAvailable',
    setContainerVisible = 'facetedFilters/setContainerVisible',
    toggleContainerVisible = 'facetedFilters/toggleContainerVisible',
    reset = 'facetedFilters/reset',
}
