version: "3.8"

services:
  geoss-haproxy:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_haproxy:${DOCKER_IMAGE_TAG}
    hostname: geoss-dmz-haproxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.group_tag==geoss-proxy"
    environment:
      DEPLOY_ENV: uat
      http_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      https_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      no_proxy: 127.0.0.1,localhost,geoss-dmz-haproxy,geoss-dmz-postfix,geoss-dmz-nginx,geoss-dmz-squid,geoss-dmz-cvupdate
    sysctls:
      - net.ipv4.tcp_max_syn_backlog=16384
      - net.ipv4.tcp_syn_retries=2
      - net.ipv4.tcp_synack_retries=1
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /etc/ssl/geoss_certs/geoss_haproxy/server.pem:/usr/local/etc/haproxy/certs/server.pem
    networks:
      - geossdmz

  geoss-nginx:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_nginx:${DOCKER_IMAGE_TAG}
    hostname: geoss-dmz-nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.group_tag==geoss-proxy"
      update_config:
        parallelism: 1
        order: start-first
    environment:
      UI_UPSTREAM_HOST: ${NGINX_UPSTREAM_HOST}
      UI_UPSTREAM_PORT: ${NGINX_CMS_UPSTREAM_PORT}
      UI_DOMAIN_NAME: gpp.uat.esaportal.eu
      UI_SERVICES_PROVIDERS: "http://yp.geodab.eu/yp-publisher/services/yp/providers"
      KEYCLOAK_UPSTREAM_HOST: ${NGINX_UPSTREAM_HOST}
      KEYCLOAK_DOMAIN_NAME: gpp-idp.uat.esaportal.eu
      ADMIN_UPSTREAM_HOST: ${NGINX_UPSTREAM_HOST}
      ADMIN_DOMAIN_NAME: gpp-admin.uat.esaportal.eu
      #MONITORING_UPSTREAM_HOST: ${NGINX_MONITORING_UPSTREAM_HOST}
      CSP_DOMAINS: 'gpp.uat.esaportal.eu,gpp-idp.uat.esaportal.eu,gpp-admin.uat.esaportal.eu'
      MAINTENANCE_WHITELIST: ${NGINX_MAINTENANCE_WHITELIST}
      DEPLOY_ENV: uat
      http_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      https_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      no_proxy: 127.0.0.1,localhost,geoss-dmz-haproxy,geoss-dmz-postfix,geoss-dmz-nginx,geoss-dmz-squid,geoss-dmz-cvupdate
    volumes:
      - /etc/ssl/geoss_certs/geoss_nginx/server.crt:/etc/nginx/certs/server.crt
      - /etc/ssl/geoss_certs/geoss_nginx/server.key:/etc/nginx/certs/server.key
      - /var/log/nginx:/var/log/nginx
    networks:
      - geossdmz

  # postfix:
  #   image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_postfix_relay:${DOCKER_IMAGE_TAG}
  #   hostname: geoss-dmz-postfix
  #   deploy:
  #     replicas: 1
  #   environment:
  #     maildomain: ${SMTP_MAIL_DOMAIN}
  #     smtp_credentials: ${SMTP_USER}:${SMTP_PASS}
  #     permit_networks: ${POSTFIX_PERMIT_NETWORKS}
  #     http_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
  #     https_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
  #     no_proxy: 127.0.0.1,localhost,geoss-dmz-haproxy,geoss-dmz-postfix,geoss-dmz-nginx,geoss-dmz-squid,geoss-dmz-cvupdate
  #   ports:
  #     - "25:25"
  #   networks:
  #     - geossdmz

  squid:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_squid:${DOCKER_IMAGE_TAG}
    hostname: geoss-dmz-squid
    deploy:
      replicas: 1
    environment:
      SQUID_PROXY_PASSWORD: ${SQUID_PROXY_PASSWORD}
    volumes:
      - /var/log/docker-squid:/var/log/squid
    ports:
      - "3128:3128"
    networks:
      - geossdmz

  cvupdate:
    image: nexus-docker.eversis.com:7443/common/cvupdate:1.0.0
    hostname: geoss-dmz-cvupdate
    deploy:
      replicas: 1
    environment:
      http_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      https_proxy: http://squid:${SQUID_PROXY_PASSWORD}@geoss-dmz-squid:3128
      no_proxy: 127.0.0.1,localhost,geoss-dmz-haproxy,geoss-dmz-postfix,geoss-dmz-nginx,geoss-dmz-squid,geoss-dmz-cvupdate
    ports:
      - "8001:8001"
    networks:
      - geossdmz

networks:
  geossdmz:
