version: "3.8"

services:
  geoss-haproxy-lan:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_haproxy_lan:${DOCKER_IMAGE_TAG}
    hostname: geoss-haproxy
    deploy:
      replicas: 1
    environment:
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
    networks:
      - geosslan

  geoss-db:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_db
    hostname: geoss-mariadb
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.unique_tag==geoss-db-1"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_USER: admin
      MARIADB_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: geoss_db
      MATOMO_DATABASE_USERNAME: ${MATOMO_DB_USER_NAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DB_USER_PASS}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DB_NAME}
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - geosslan

  geoss-keycloak:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_keycloak:${DOCKER_IMAGE_TAG}
    command: [ "start", "--optimized", "--import-realm", "--spi-theme-welcome-theme=geoss", "--https-certificate-file=/etc/x509/https/dev/tls.crt", "--https-certificate-key-file=/etc/x509/https/dev/tls.key" ]
    hostname: geoss-keycloak
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.unique_tag==geoss-db-1"
    environment:
      KC_DB: mariadb
      KC_DB_URL: "jdbc:mariadb://geoss-db:3306/geoss_keycloak_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useSSL=false&allowPublicKeyRetrieval=true"
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: ${DB_ROOT_PASS}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ROOT_PASS}
      KC_HOSTNAME: gpp-idp.devel.esaportal.eu
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: "true"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8443:8443"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-maildev

  geoss-settings:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_settings:${DOCKER_IMAGE_TAG}
    hostname: geoss-settings
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_settings_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DS_PASS}
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_SETTINGS_OA2_KCSECRET}
      KEYTOOL_STOREPASS: notusedyet
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8080:8080"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-personaldata:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_personaldata:${DOCKER_IMAGE_TAG}
    hostname: geoss-personaldata
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_personaldata_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DS_PASS}
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_PERSONALDATA_OA2_KCSECRET}
      KEYTOOL_STOREPASS: notusedyet
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8083:8080"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-contents:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_contents:${DOCKER_IMAGE_TAG}
    hostname: geoss-contents
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_contents_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DS_PASS}
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_CONTENTS_OA2_KCSECRET}
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8082:8081"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak
    volumes:
      - /nfs/data:/repository

  geoss-admin:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_admin:${DOCKER_IMAGE_TAG}
    hostname: geoss-admin
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      NEXT_PUBLIC_API: "https://gpp-admin.devel.esaportal.eu"
      NEXT_PUBLIC_APP_URL: "https://gpp.devel.esaportal.eu"
      NEXT_PUBLIC_URL: "https://gpp-admin.devel.esaportal.eu"
      NEXTAUTH_URL: "https://gpp-admin.devel.esaportal.eu"
      NEXTAUTH_SECRET: "d3fa4c4ff9e3a252247fca2e74e5f585"
      KEYCLOAK_CLIENT_ID: "geoss-admin"
      KEYCLOAK_CLIENT_SECRET: ${GEOSS_ADMIN_OA2_KCSECRET}
      KEYCLOAK_BASE_URL: "https://gpp-idp.devel.esaportal.eu/realms/geoss"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "3000:3000"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-ui:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_ui:${DOCKER_IMAGE_TAG}
    hostname: geoss-ui
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      API_URL: http://gpp.devel.esaportal.eu
      BASE_URL: https://gpp.devel.esaportal.eu
      ADMIN_URL: https://gpp-admin.devel.esaportal.eu
      KEYCLOAK_CLIENT_ID: geoss-ui
      KEYCLOAK_BASE_URL: https://gpp-idp.devel.esaportal.eu/realms/geoss
      MATOMO_SITE_ID: 1
      MATOMO_TOKEN: '5476ec8e5eec12f0fec9f0543ac9552c'
      NODE_OPTIONS: "--max-old-space-size=4096"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "3001:3000"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-maildev:
    hostname: geoss-maildev
    image: nexus-docker.eversis.com:7443/common/maildev:1.0.0
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      MAILDEV_INCOMING_USER: maildev
      MAILDEV_INCOMING_PASS: ${MAILDEV_SMTP_PASSWORD}
      MAILDEV_WEB_USER: admin
      MAILDEV_WEB_PASS: ${MAILDEV_WEB_PASSWORD}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "1081:1080"
    logging:
      driver: "json-file"
      options:
        max-file: 300
        max-size: 10m
    networks:
      - geosslan

  geoss-proxy:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_proxy:${DOCKER_IMAGE_TAG}
    hostname: geoss-proxy
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      SPRING_ELASTICSEARCH_REST_URIS: geoss-elasticsearch-1:9200
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_PROXY_OA2_KCSECRET}
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    ports:
      - "8084:8082"
    networks:
      - geosslan
    depends_on:
      - geoss-elasticsearch-1
      - geoss-keycloak

  geoss-curated:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_curated:${DOCKER_IMAGE_TAG}
    hostname: geoss-curated
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_curated_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DS_PASS}
      SPRING_ELASTICSEARCH_REST_URIS: geoss-elasticsearch-1:9200
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_CURATED_OA2_KCSECRET}
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    restart: always
    ports:
      - "8085:8080"
    networks:
      - geosslan
    depends_on:
      - geoss-db
      - geoss-keycloak
      - geoss-elasticsearch-1

  geoss-search:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_search:${DOCKER_IMAGE_TAG}
    hostname: geoss-search
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.shared_tag==geoss-apps"
    environment:
      DATASOURCE_AMERIGEOSS_CKAN_BASE_URL: "https://data.amerigeoss.org/api/3/action"
      DATASOURCE_ZENODO_BASE_URL: "https://zenodo.org"
      DATASOURCE_ELASTICSEARCH_HOST: "geoss-elasticsearch"
      DATASOURCE_ELASTICSEARCH_PORT: "9200"
      DATASOURCE_ELASTICSEARCH_COMPATIBILITYMODE: "true"
      SPRING_PROFILES_ACTIVE: keycloak
      SPRING_SECURITY_OAUTH2_BASE_URI: "https://gpp-idp.devel.esaportal.eu"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${GEOSS_SEARCH_OA2_KCSECRET}
      SERVER_MAX_HTTP_HEADER_SIZE: "32KB"
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    restart: always
    ports:
      - "8086:8080"
    networks:
      - geosslan
    depends_on:
      - geoss-keycloak
      - geoss-elasticsearch-1

  geoss-elasticsearch-1:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_els:${DOCKER_IMAGE_TAG}
    hostname: geoss-elasticsearch-1
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.unique_tag==geoss-elastic-1"
    environment:
      node.name: geoss-elasticsearch-1
      cluster.name: geoss-elasticsearch
      #      - discovery.seed_hosts=geoss-elasticsearch-2,geoss-elasticsearch-3
      #      - cluster.initial_master_nodes=geoss-elasticsearch-1,geoss-elasticsearch-2,geoss-elasticsearch-3
      #      - bootstrap.memory_lock=true
      network.publish_host: geoss-elasticsearch-1
      discovery.type: single-node
      http.max_content_length: 1000mb
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      ELASTICSEARCH_KEYS: "xpack.security.authc.realms.oidc.geoss.rp.client_secret=xTUIINx6U7qe6lcTcrRUdgYqVKo08dXs"
      BITNAMI_DEBUG: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/lib/elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - geosslan

  geoss-kibana:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_kibana:${DOCKER_IMAGE_TAG}
    hostname: geoss-kibana
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.unique_tag==geoss-elastic-1"
    environment:
      KIBANA_ELASTICSEARCH_URL: geoss-elasticsearch-1
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${KIBANA_OA2_KCSECRET}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    volumes:
      - /opt/kibana:/bitnami/kibana
    ports:
      - "5601:5601"
    networks:
      - geosslan
    depends_on:
      - geoss-elasticsearch-1

  geoss-matomo:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_matomo:${DOCKER_IMAGE_TAG}
    hostname: geoss-matomo
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.shared_tag==geoss-matomo"
    environment:
      MATOMO_DATABASE_HOST: "geoss-mariadb"
      MATOMO_DATABASE_PORT_NUMBER: 3306
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_USER: ${MATOMO_DB_USER_NAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DB_USER_PASS}
      MATOMO_DATABASE_NAME: ${MATOMO_DB_NAME}
      MATOMO_USERNAME: "admin"
      MATOMO_PASSWORD: "qaz123"
      MATOMO_ENABLE_PROXY_URI_HEADER: "yes"
      MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL: "yes"
      MATOMO_DATABASE_TABLE_PREFIX: "${MATOMO_DB_PREFIX}"
      SPRING_SECURITY_OAUTH2_CLIENT_SECRET: ${MATOMO_OA2_KCSECRET}
      http_proxy: ${SQUID_PROXY_URL}
      https_proxy: ${SQUID_PROXY_URL}
      no_proxy: 127.0.0.1,localhost,geoss-haproxy-lan,geoss-db,geoss-keycloak,geoss-settings,geoss-personaldata,geoss-contents,geoss-admin,geoss-ui,geoss-maildev,geoss-proxy,geoss-elasticsearch-1,geoss-kibana,geoss-matomo,geoss-curated,geoss-search
    volumes:
      - /var/log/matomo:/var/log
    networks:
      - geosslan
    depends_on:
      - geoss-db

  #######################################
  #          HELPER CONTAINERS          #
  #######################################
  # backup-mariadb:
  #   image: nexus-docker.eversis.com:7443/common/backup_mariadb:1.0.0
  #   hostname: geoss-backup-mariadb
  #   deploy:
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - "node.labels.unique_tag==geoss-database-1"
  #   environment:
  #     MYSQL_HOST: "geoss-mariadb"
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: geossuser
  #     MYSQL_PASS: ${DB_ROOT_PASS}
  #     CRON_TIME: "0 3 * * *"
  #     GZIP_LEVEL: 9
  #     MYSQLDUMP_OPTS: "--no-tablespaces"
  #     TZ: "Europe/Warsaw"
  #     http_proxy: ${SQUID_PROXY_URL}
  #     https_proxy: ${SQUID_PROXY_URL}
  #     no_proxy: 127.0.0.1,localhost
  #   volumes:
  #     - /opt/backup:/backup
  #   networks:
  #     - geosslan

networks:
  geosslan:
