version: '3.8'

services:

########################
###    DMZ IMAGES    ###
########################
  geoss-nginx:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_nginx:${DOCKER_IMAGE_TAG}
    container_name: geoss-nginx
    build:
      context: ./geoss-nginx
      dockerfile: Dockerfile

  geoss-haproxy:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_haproxy:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-haproxy
      dockerfile: Dockerfile

  geoss-squid:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_squid:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-squid
      dockerfile: Dockerfile

########################
###    LAN IMAGES    ###
########################
  geoss-admin:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_admin:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-admin
      dockerfile: Dockerfile

  # geoss-bookmarks:
  #   image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_bookmarks:${DOCKER_IMAGE_TAG}
  #   build:
  #     context: ./geoss-bookmarks
  #     dockerfile: Dockerfile

  geoss-contents:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_contents:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-contents
      dockerfile: Dockerfile

  geoss-curated:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_curated:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-curated
      dockerfile: Dockerfile

  geoss-db:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_db:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-db
      dockerfile: Dockerfile

  geoss-els:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_els:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-els
      dockerfile: Dockerfile

  geoss-haproxy-lan:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_haproxy_lan:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-haproxy-lan
      dockerfile: Dockerfile

  geoss-keycloak:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_keycloak:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-keycloak
      dockerfile: Dockerfile
      args:
        KC_DB: mariadb

  geoss-kibana:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_kibana:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-kibana
      dockerfile: Dockerfile

  geoss-matomo:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_matomo:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-matomo
      dockerfile: Dockerfile

  geoss-personaldata:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_personaldata:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-personaldata
      dockerfile: Dockerfile

  geoss-proxy:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_proxy:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-proxy
      dockerfile: Dockerfile

  geoss-search:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_search:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-search
      dockerfile: Dockerfile

  geoss-settings:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_settings:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-settings
      dockerfile: Dockerfile

  geoss-ui:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_ui:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-ui
      dockerfile: Dockerfile

  geoss-worker-geodab-worker:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_worker_geodab_worker:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-worker/entry-worker/geodab-worker
      dockerfile: Dockerfile

  geoss-worker-sdg-worker:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_worker_sdg_worker:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-worker/entry-worker/sdg-worker
      dockerfile: Dockerfile

  geoss-worker-wikipedia-worker:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_worker_wikipedia_worker:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-worker/entry-worker/wikipedia-worker
      dockerfile: Dockerfile

  geoss-worker_thesaurus_worker:
    image: nexus-docker.eversis.com:7443/geoss-mst-images/geoss_worker_thesaurus_worker:${DOCKER_IMAGE_TAG}
    build:
      context: ./geoss-worker/thesaurus-worker
      dockerfile: Dockerfile
