version: "3.8"

services:

    geoss-db:
        container_name: geoss-db
        build:
            context: ./geoss-db
            dockerfile: Dockerfile
        environment:
            MARIADB_ROOT_PASSWORD: qaz123
            MARIADB_USER: admin
            MARIADB_PASSWORD: qaz123
            MARIADB_DATABASE: geoss_db
        volumes:
            - "geoss_db:/var/lib/mysql"
        ports:
            - "33066:3306"
        networks:
          - geoss_net

    geoss-keycloak:
        container_name: geoss-keycloak
        build:
            context: ./geoss-keycloak
            dockerfile: Dockerfile
            args:
                KC_DB: mariadb
        command: ["start-dev", "--import-realm", "--spi-theme-welcome-theme=geoss"]
        environment:
            KC_DB: mariadb
            KC_DB_URL: "jdbc:mariadb://geoss-db:3306/geoss_keycloak_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
            KC_DB_USERNAME: admin
            KC_DB_PASSWORD:  qaz123
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: qaz123
            KC_HOSTNAME: geoss-keycloak
            KC_HOSTNAME_STRICT: "false"
            KC_SPI_THEME_CACHE_THEMES: "false"
            KC_SPI_THEME_CACHE_TEMPLATES: "false"
            KC_SPI_THEME_STATIC_MAX_AGE: "-1"
        volumes:
            - "./geoss-keycloak/themes/geoss:/opt/keycloak/themes/geoss"
        ports:
            - "8080:8080"
        networks:
            - geoss_net

    geoss-settings:
        container_name: geoss-settings
        build:
            context: ./geoss-settings
            dockerfile: Dockerfile-local
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_settings_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: qaz123
            SPRING_SECURITY_USER_NAME: user
            SPRING_SECURITY_USER_PASSWORD: '{noop}qaz123'
            SPRING_SECURITY_USER_ROLES: USER,ADMIN
            SPRING_SECURITY_USER_EMAIL: user@geoss-settings
            SPRING_SECURITY_USER_FIRST_NAME: User
            SPRING_SECURITY_USER_LAST_NAME: User
            SPRING_PROFILES_ACTIVE: keycloak
            SPRING_SECURITY_OAUTH2_BASE_URI: "http://geoss-keycloak:8080"
            SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
            SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET: uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
        ports:
            - "8088:8080"
        networks:
            - geoss_net
        depends_on:
            - geoss-db
            - geoss-keycloak

    geoss-userdata:
        container_name: geoss-userdata
        build:
            context: ./geoss-userdata
            dockerfile: Dockerfile-local
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mariadb://geoss-db:3306/geoss_userdata_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: qaz123
            SPRING_SECURITY_USER_NAME: user
            SPRING_SECURITY_USER_PASSWORD: '{noop}qaz123'
            SPRING_SECURITY_USER_ROLES: USER,ADMIN
            SPRING_SECURITY_USER_EMAIL: user@geoss-userdata
            SPRING_SECURITY_USER_FIRST_NAME: User
            SPRING_SECURITY_USER_LAST_NAME: User
            SPRING_PROFILES_ACTIVE: keycloak
            SPRING_SECURITY_OAUTH2_BASE_URI: "http://geoss-keycloak:8080"
            SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
            SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET: uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
        ports:
            - "8089:8080"
        networks:
            - geoss_net
        depends_on:
            - geoss-db
            - geoss-keycloak

    geoss-contents:
        container_name: geoss-contents
        build:
            context: ./geoss-contents
            dockerfile: Dockerfile-local
        ports:
            - "8081:8081"
        networks:
            - geoss_net

volumes:
    geoss_db:

networks:
    geoss_net:
