version: "3.8"

services:
  geoss-contents:
    image: geoss-contents
    build:
      context: ./geoss-contents
      dockerfile: Dockerfile-local
    container_name: geoss-contents
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_contents_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
    hostname: geoss-contents
    ports:
      - "8081:8081"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-curated:
    image: geoss-curated
    build:
      context: .
      dockerfile: ./geoss-curated/Dockerfile-local
    container_name: geoss-curated
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_curated_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_ELASTICSEARCH_REST_URIS=geoss-els:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=qaz123
      - SPRING_MAIL_HOST=geoss-maildev
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=maildev
      - SPRING_MAIL_PASSWORD=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - SPRING_MAIL_PROPERTIES_MAIL_DEBUG=true
    hostname: geoss-curated
    ports:
      - "8082:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-els
      - geoss-keycloak
      - geoss-maildev

  geoss-db:
    image: geoss-db
    build:
      context: ./geoss-db
      dockerfile: Dockerfile
    container_name: geoss-db
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "164M"
    environment:
      - MARIADB_ROOT_PASSWORD=qaz123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=qaz123
      - MARIADB_DATABASE=geoss_db
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=qaz123
      - MATOMO_DATABASE_DBNAME=geoss_matomo_db
    hostname: geoss-db
    volumes:
      - "geoss_db:/var/lib/mysql"
    ports:
      - "33066:3306"
    networks:
      - geoss_net

  geoss-els:
    image: geoss-els
    build:
      context: ./geoss-els
      dockerfile: Dockerfile
    container_name: geoss-els
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic123
      - KIBANA_PASSWORD=kibana123
      - GEOSS_PASSWORD=qaz123
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: curl --user elastic:elastic123 -sS "http://localhost:9200/_cat/health?h=status" | grep -q "green\|yellow" || exit 1
      interval: 30s
      start_period: 30s
      timeout: 1m
    hostname: geoss-els
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "geoss_els:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - geoss_net

  geoss-haproxy:
    image: geoss-haproxy
    build:
      context: ./local/geoss-haproxy
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "64M"
    container_name: geoss-haproxy
    environment:
      - FOO=BAR
    hostname: geoss-haproxy
    ports:
      - "8011:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    networks:
      - geoss_net

  geoss-keycloak:
    image: geoss-keycloak
    build:
      context: ./geoss-keycloak
      dockerfile: Dockerfile
      args:
        KC_DB: mariadb
    container_name: geoss-keycloak
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "start-dev", "--import-realm", "--spi-theme-welcome-theme=geoss", "--hostname-debug=true" ]
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://geoss-db:3306/geoss_keycloak_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=qaz123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=qaz123
      - KC_SPI_THEME_CACHE_THEMES=false
      - KC_SPI_THEME_CACHE_TEMPLATES=false
      - KC_SPI_THEME_STATIC_MAX_AGE=-1
      - KC_HEALTH_ENABLED=true
      - KC_PROXY=edge
    healthcheck:
      test: /opt/utils/health-check.sh
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 5s
    hostname: geoss-keycloak
    ports:
      - "8080:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-maildev

  geoss-kibana:
    image: geoss-kibana
    build:
      context: ./geoss-kibana
      dockerfile: Dockerfile
    container_name: geoss-kibana
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
    environment:
      - KIBANA_ELASTICSEARCH_URL=geoss-els
      - KIBANA_PASSWORD=kibana123
      - GEOSS_PASSWORD=qaz123
    hostname: geoss-kibana
    ports:
      - "5601:5601"
    networks:
      - geoss_net
    depends_on:
      - geoss-els

  geoss-matomo:
    image: geoss-matomo
    build:
      context: ./geoss-matomo
      dockerfile: Dockerfile
    container_name: geoss-matomo
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "128M"
    environment:
      - MATOMO_DATABASE_HOST=geoss-db
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_NAME=geoss_matomo_db
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_PASSWORD=qaz123
      - MATOMO_DATABASE_TABLE_PREFIX=matomo_
      - MATOMO_SMTP_HOST=geoss-maildev
      - MATOMO_SMTP_PORT=1025
      - MATOMO_SMTP_USER=maildev
      - MATOMO_SMTP_PASSWORD=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - MATOMO_USERNAME=admin
      - MATOMO_PASSWORD=qaz123
      - MATOMO_EMAIL=admin@gpp.com
      - MATOMO_WEBSITE_NAME=geoss-ui
      - MATOMO_WEBSITE_HOST=http://geoss-ui
      - MATOMO_ENABLE_PROXY_URI_HEADER=true
      - MATOMO_PROXY_CLIENT_HEADER=HTTP_X_FORWARDED_FOR
      - MATOMO_PROXY_HOST_HEADER=HTTP_X_FORWARDED_HOST
    hostname: geoss-matomo
    ports:
      - "8008:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-maildev

  geoss-nginx:
    image: geoss-nginx
    build:
      context: ./local/geoss-nginx
      dockerfile: Dockerfile
    container_name: geoss-nginx
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "32M"
    environment:
      - UI_DOMAIN_NAME=gpp-ui
      - UI_UPSTREAM_HOST=geoss-haproxy
      - UI_UPSTREAM_PORT=8001
      - ADMIN_DOMAIN_NAME=gpp-admin
      - ADMIN_UPSTREAM_HOST=geoss-haproxy
      - ADMIN_UPSTREAM_PORT=8002
      - IDP_DOMAIN_NAME=gpp-idp
      - IDP_UPSTREAM_HOST=geoss-haproxy
      - IDP_UPSTREAM_PORT=8003
    hostname: geoss-nginx
    ports:
      - "80:80"
    networks:
      - geoss_net

  geoss-personaldata:
    image: geoss-personaldata
    build:
      context: .
      dockerfile: ./geoss-personaldata/Dockerfile-local
    container_name: geoss-personaldata
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_personaldata_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
    hostname: geoss-personaldata
    ports:
      - "8083:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-proxy:
    image: geoss-proxy
    build:
      context: ./geoss-proxy
      dockerfile: Dockerfile-local
    container_name: geoss-proxy
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_ELASTICSEARCH_REST_URIS=geoss-els:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
    hostname: geoss-proxy
    ports:
      - "8084:8082"
    networks:
      - geoss_net
    depends_on:
      - geoss-els
      - geoss-keycloak

  geoss-search:
    image: geoss-search
    build:
      context: ./geoss-search
      dockerfile: Dockerfile-local
    container_name: geoss-search
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - DATASOURCE_AMERIGEOSS_CKAN_BASE_URL=https://data.amerigeoss.org/api/3/action
      - DATASOURCE_ZENODO_BASE_URL=https://zenodo.org
      - DATASOURCE_ELASTICSEARCH_HOST=geoss-els
      - DATASOURCE_ELASTICSEARCH_PORT=9200
      - DATASOURCE_ELASTICSEARCH_USERNAME=elastic
      - DATASOURCE_ELASTICSEARCH_PASSWORD=elastic123
      - DATASOURCE_ELASTICSEARCH_COMPATIBILITYMODE=true
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
    hostname: geoss-search
    ports:
      - "8085:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-els
      - geoss-keycloak

  geoss-settings:
    image: geoss-settings
    build:
      context: .
      dockerfile: ./geoss-settings/Dockerfile-local
    container_name: geoss-settings
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_settings_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
    hostname: geoss-settings
    ports:
      - "8086:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-keycloak

  geoss-worker-geodab-worker:
    image: geoss-worker-geodab-worker
    build:
      context: .
      dockerfile: ./geoss-worker/entry-worker/geodab-worker/Dockerfile-local
    container_name: geoss-worker-geodab-worker
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_curated_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - CONFIG_DAB_GEODAB_BASE_URL=https://pqqsdba4n9.execute-api.us-east-1.amazonaws.com/alpha
      - CONFIG_DAB_VLAB_BASE_URL=https://vlabdev.geodab.org/vlab
      - CONFIG_DAB_VLAB_API_TOKEN=7qm9uezuj27SjqE7FTAEj3iNeKbmpRaHasg7zVs3
    hostname: geoss-worker-geodab-worker
    ports:
      - "8087:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-curated
      - geoss-keycloak

  geoss-worker-sdg-worker:
    image: geoss-worker-sdg-worker
    build:
      context: .
      dockerfile: ./geoss-worker/entry-worker/sdg-worker/Dockerfile-local
    container_name: geoss-worker-sdg-worker
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_curated_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - CONFIG_SDG_DEFAULT_LOGO=https://unstats.un.org/home/assets/img/logos/logo_StatisticsDivision.png
      - CONFIG_SDG_UN_BASE_URL=https://unstats.un.org/SDGAPI/v1/sdg
    hostname: geoss-worker-sdg-worker
    ports:
      - "8088:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-curated
      - geoss-keycloak

  geoss-worker-wikipedia-worker:
    image: geoss-worker-wikipedia-worker
    build:
      context: .
      dockerfile: ./geoss-worker/entry-worker/wikipedia-worker/Dockerfile-local
    container_name: geoss-worker-wikipedia-worker
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://geoss-db:3306/geoss_curated_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qaz123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - WIKIDATA_API_URL=https://en.wikipedia.org/w/api.php
      - WIKIDATA_CATEGORIES_SPARQL_URL=https://live.dbpedia.org/sparql
      - WIKIDATA_CATEGORIES_SPARQL_DEFAULT_GRAPH_URI=https://dbpedia.org
    hostname: geoss-worker-wikipedia-worker
    ports:
      - "8089:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-db
      - geoss-curated
      - geoss-keycloak

  geoss-worker-thesaurus-worker:
    image: geoss-worker-thesaurus-worker
    build:
      context: .
      dockerfile: ./geoss-worker/thesaurus-worker/Dockerfile-local
    container_name: geoss-worker-thesaurus-worker
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
    command: [ "--debug" ]
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://geoss-els:9200
      - SPRING_ELASTICSEARCH_USERNAME=elastic
      - SPRING_ELASTICSEARCH_PASSWORD=elastic123
      - SPRING_PROFILES_ACTIVE=keycloak
      - SPRING_SECURITY_OAUTH2_BASE_URI=http://geoss-keycloak:8080
      - SPRING_SECURITY_OAUTH2_CLIENT_SECRET=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - THESAURUS_ESA_BASE_URI=https://thesauri.eo.esa.int/rest/v1/thesaurus/data
      - THESAURUS_ESA_TOP_CONCEPTS_URIS=https://earth.esa.int/concept/5c476560-e0a3-554a-9187-187a90da1309,https://earth.esa.int/concept/c98c8eae-7561-55de-bf01-2fb866693c14,https://earth.esa.int/concept/738c519f-48db-5344-bebc-030c16781c22
      - THESAURUS_EOSTERM_BASE_URI=https://vocabularyserver.com/cnr/ml/eosterm/en/services.php
      - THESAURUS_EARTH_BASE_URI=https://vocabularyserver.com/cnr/ml/earth/en/services.php
    hostname: geoss-worker-thesaurus-worker
    ports:
      - "8090:8080"
    networks:
      - geoss_net
    depends_on:
      - geoss-els
      - geoss-keycloak

  geoss-maildev:
    image: nexus-docker.eversis.com:7443/common/maildev:1.0.0
    container_name: geoss-maildev
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32M"
    environment:
      - MAILDEV_INCOMING_USER=maildev
      - MAILDEV_INCOMING_PASS=uTUIINx6U7qe6lcTcrRUdgYqVKo08dXs
      - MAILDEV_WEB_USER=admin
      - MAILDEV_WEB_PASS=qaz123
    hostname: geoss-maildev
    ports:
      - "1081:1080"
      - "1025:1025"
    networks:
      - geoss_net

volumes:
  geoss_db:
  geoss_els:

networks:
  geoss_net:
