version: '2.2'
services:
    elk:
        image: geoss-cr-elk:6.6.1.0
        ports:
            - "9200:9200"
            - "5601:5601"
        networks:
            - geoss-cr-network
        volumes:
            - elk-data:/var/lib/elasticsearch
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 15s
            timeout: 10s
            retries: 40
networks:
    geoss-cr-network:
volumes:
    elk-data:


