FROM bitnami/matomo:4.15.1

LABEL vendor="Eversis"
LABEL maintainer="Eversis"
LABEL project="GEOSS"
LABEL version="1.0"
LABEL image="geoss-matomo"

COPY --chown=1001 conf/global.ini.php /bitnami/matomo/config/global.ini.php