apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoss-maildev.fullname" . }}
  labels:
    {{- include "geoss-maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "geoss-maildev.selectorLabels" . | nindent 4 }}
