FROM openjdk:21-jdk-slim AS builder

ENV TZ=UTC
ENV LANG=en_GB.UTF-8 LANGUAGE=en_GB:en
ENV GRADLE_USER_HOME=/opt/app/.gradle

WORKDIR /opt/app

COPY ./ ./

RUN chmod u+x gradlew
RUN ./gradlew --build-cache --no-daemon assemble


FROM openjdk:21-jdk-slim AS runner

LABEL vendor="Eversis"
LABEL maintainer="Eversis"
LABEL project="GEOSS"
LABEL version="1.0"
LABEL image="geoss-proxy"

ENV TZ=UTC
ENV LANG=en_GB.UTF-8 LANGUAGE=en_GB:en
ENV JAVA_OPTS="${JAVA_OPTS} \
-server \
-Dfile.encoding=UTF-8 \
-Dsun.jnu.encoding=UTF-8 \
-Duser.country=GB \
-Duser.language=en \
-Duser.timezone=GMT \
"
ENV JDK_JAVA_OPTIONS=$JAVA_OPTS
ENV JAVA_TOOL_OPTIONS="-Djava.io.tmpdir=tomcat/temp"

WORKDIR /opt/app

ARG JAR_FILE=/opt/app/build/libs/geoss-proxy-*-boot.jar
COPY --from=builder ${JAR_FILE} ./application-boot.jar

RUN mkdir -p "tomcat/temp"

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "application-boot.jar"]
CMD [""]
