export enum IrisFiltersActions {
    setMagnitudeType = 'irisFilters/setMagnitudeType',
    setMagnitudeTypeOptions = 'irisFilters/setMagnitudeTypeOptions',
    setSort = 'irisFilters/setSort',
    setSortOptions = 'irisFilters/setSortOptions',
    setMinMagnitude = 'irisFilters/setMinMagnitude',
    setMaxMagnitude = 'irisFilters/setMaxMagnitude',
    setMinDepth = 'irisFilters/setMinDepth',
    setMaxDepth = 'irisFilters/setMaxDepth',
    setDateFrom = 'irisFilters/setDateFrom',
    setDateTo = 'irisFilters/setDateTo',
    setContainerVisible = 'irisFilters/setContainerVisible',
    toggleContainerVisible = 'irisFilters/toggleContainerVisible',
    setIrisFiltersAvailable = 'irisFilters/setIrisFiltersAvailable',
    reset = 'irisFilters/reset',
}
