export enum FacetedFiltersGetters {
    state = 'facetedFilters/state',
    keyword = 'facetedFilters/keyword',
    keywordOptions = 'facetedFilters/keywordOptions',
    format = 'facetedFilters/format',
    formatOptions = 'facetedFilters/formatOptions',
    source = 'facetedFilters/source',
    sourceOptions = 'facetedFilters/sourceOptions',
    protocol = 'facetedFilters/protocol',
    protocolOptions = 'facetedFilters/protocolOptions',
    organisation = 'facetedFilters/organisation',
    organisationOptions = 'facetedFilters/organisationOptions',
    score = 'facetedFilters/score',
    scoreOptions = 'facetedFilters/scoreOptions',
    facetedFiltersAvailable = 'facetedFilters/facetedFiltersAvailable',
    containerVisible = 'facetedFilters/containerVisible',
    stateMapped = 'facetedFilters/stateMapped',
    shareParams = 'facetedFilters/shareParams',
    saveParams = 'facetedFilters/saveParams'
}
