datasource:
    amerigeoss-ckan:
        base-url: https://data.amerigeoss.org/api/3/action
    zenodo:
        base-url: https://zenodo.org
    elasticsearch:
        host: localhost
        port: 9200
        geoss:
            index: geoss-cr
            type: _doc
        thesaurus:
            index: thesaurus-vocabulary
            type: vocabulary


logging:
    config: file:config/log4j2-prod.xml


