{{- range .Values.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .name }}
type: kubernetes.io/tls
data:
  tls.crt: {{- $.Files.Get .certFile | b64enc | quote | nindent 4 }}
  tls.key: {{- $.Files.Get .certKey | b64enc | quote | nindent 4 }}
{{- end }}
