apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoss-personaldata.fullname" . }}
  labels:
    {{- include "geoss-personaldata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "geoss-personaldata.selectorLabels" . | nindent 4 }}
