import React from "react";
import parse from "html-react-parser";
import Link from "next/link";
import GeneralButton from "@/src/app/components/GeneralButton";
import Image from "next/image";

const getServerSideProps = (id: string) => {
  //placeholder to fetch article data in form of html
  //const articleData = await fetch(`https://.../${id}`).then((res) => res.json())
  return {
    title: "Article title example",
    date: "27.05.2024",
    img: "/1.webp",
    text: `<div>
      <h1>Understanding Quantum Entanglement</h1>
    <p class="author">John Doe<sup>1</sup>, Jane Smith<sup>2</sup></p>
    <p><sup>1</sup>Department of Physics, University of Example, City, Country</p>
    <p><sup>2</sup>Institute of Advanced Studies, University of Science, City, Country</p>

    <section class="abstract">
        <h2>Abstract</h2>
        <p>This article explores the phenomenon of quantum entanglement, its implications in modern physics, and potential applications in quantum computing. Our findings suggest significant advancements in the understanding of entangled particles, paving the way for future research.</p>
    </section>

    <section class="introduction">
        <h2>Introduction</h2>
        <p>Quantum entanglement is one of the most intriguing aspects of quantum mechanics. First described by Einstein, Podolsky, and Rosen in 1935, this phenomenon challenges the classical understanding of physics. This article delves into the history, theory, and experimental evidence surrounding quantum entanglement.</p>
    </section>

    <section class="methods">
        <h2>Methods</h2>
        <p>We conducted a series of experiments using entangled photons generated by spontaneous parametric down-conversion. The setup involved a nonlinear crystal and a laser source, as illustrated in <a href="#figure1">Figure 1</a>.</p>
        <img src="/1.webp" alt="Experimental setup for generating entangled photons" id="figure1">
        <p>Figure 1: Experimental setup for generating entangled photons.</p>
    </section>

    <section class="results">
        <h2>Results</h2>
        <p>The results of our experiments indicate a high degree of correlation between the entangled particles. The correlation coefficient was found to be 0.98, supporting the non-locality hypothesis of quantum mechanics.</p>
        <p>For more detailed data, see <a href="https://www.examplejournal.com/article/data" target="_blank">Supplementary Material</a>.</p>
    </section>

    <section class="discussion">
        <h2>Discussion</h2>
        <p>The results confirm previous studies and open new avenues for research in quantum computing and secure communication. The observed entanglement fidelity suggests that these systems could be employed in practical applications, such as quantum key distribution.</p>
    </section>

    <section class="conclusion">
        <h2>Conclusion</h2>
        <p>In conclusion, our research contributes to the growing body of evidence supporting quantum entanglement as a fundamental aspect of quantum mechanics. Future studies should focus on scaling up these experiments for practical quantum computing applications.</p>
    </section>

    <section class="references">
        <h2>References</h2>
        <div class="reference">
            [1] Einstein, A., Podolsky, B., & Rosen, N. (1935). Can Quantum-Mechanical Description of Physical Reality be Considered Complete? *Physical Review*, 47(10), 777-780.
        </div>
        <div class="reference">
            [2] Aspect, A., Grangier, P., & Roger, G. (1982). Experimental Realization of Einstein-Podolsky-Rosen-Bohm Gedankenexperiment: A New Violation of Bell's Inequalities. *Physical Review Letters*, 49(2), 91-94. <a href="https://doi.org/10.1103/PhysRevLett.49.91" target="_blank">https://doi.org/10.1103/PhysRevLett.49.91</a>
        </div>
    </section>
    <div>
  `,
  };
};

const page = async ({ params }: { params: { id: string } }) => {
  try {
    const articleData = await getServerSideProps(params.id);
    return (
      <div className="w-full flex flex-col items-start px-6 lg:px-72 xl:px-96 2xl:px-[32rem] 3xl:px-[48rem] py-16 lg:py-24 gap-8 text-black">
        <div className="w-full flex flex-row gap-4 text-2xl">
          <Link className="text-[#5C6369]" href="/news">
            News
          </Link>
          <p className="text-[#5C6369]">{"/"}</p>
          <p>{articleData.title}</p>
        </div>
        <div className="relative w-full h-[50vh] object-cover object-center">
          <Image
            loading="eager"
            fill
            style={{
              objectFit: "cover",
              objectPosition: "center",
            }}
            alt="news-image"
            src={articleData.img}
          />
        </div>
        <h2 className="text-5xl ">{articleData.title}</h2>
        <p className="text-[#23272A] text-2xl">{articleData.date}</p>
        <div className="article-content">{parse(articleData.text)}</div>
        <GeneralButton className="self-center" href="/news">
          Read more articles
        </GeneralButton>
      </div>
    );
  } catch (e: any) {
    return <div>Error fetching data: {JSON.stringify(e)}</div>;
  }
};

export default page;
