export const en = {
    general: {
        close: "Close",
        type: "Type here...",
        confirm: "Confirm",
        cancel: "Cancel",
        published: "Published",
        draft: "Draft",
        title: "Title",
        save: "Save",
    },
    form: {
        placeholders: {
            type: "Type here...",
            "select-one": "Select one...",
        },
        errors: {
            "invalid-email": "Invalid e-mail address",
            "invalid-url": "Invalid URL",
            "invalid-username": "Invalid username",
            "invalid-password":
                "Invalid password (at least 8 characters including a lowercase letter, an uppercase letter, number and special character)",
            "invalid-slug": "Invalid friendly URL (spaces not allowed)",
            required: "Required field",
            "passwords-not-match": "Passwords don't match",
        },
        actions: {
            submit: "Submit",
            "save-draft": "Save as draft",
            "submit-changes": "Submit changes",
            "save-changes-draft": "Save changes as draft",
        },
    },
    contents: {
        title: "Contents",
        section: {
            website: "Website",
            page: "Page",
            repository: "File repository",
        },
    },
    settings: {
        title: "Settings",
        section: {
            api: "API",
            web: "Web",
            menu: "Menu",
            catalogs: "Catalogs",
            views: "Views",
            layer: "Default layer",
            tutorial: "Tutorial tags",
        },
    },
    profile: {
        title: "Profile",
        section: {
            profile: "My profile",
            logout: "Logout",
        },
    },
    pages: {
        error: {
            info: "Oops! That page does not exist.",
        },
        contents: {
            title: "Website contents",
            add: "Add content",
            "delete-selected": "Delete selected",
            "content-title": "Title",
            author: "Author",
            "creation-date": "Creation date",
            "modification-date": "Modification date",
            actions: "Actions",
            "delete-content-title": "Content deletion",
            "delete-content-body": "Are you sure you want to remove content {title} (ID: {itemId})?",
            "preview-content-title": "Content preview (ID: {id})",
            "preview-content-body": "Preview",
            content: "Content",
            status: "Status",
        },
        "add-content": {
            title: "Add content",
            preview: "Show preview",
        },
        "edit-content": {
            title: "Content edition",
            preview: "Show preview",
        },
        page: {
            title: "Site pages",
            add: "Add page",
            "delete-selected": "Delete selected",
            "page-title": "Title",
            author: "Author",
            "creation-date": "Creation date",
            "modification-date": "Modification date",
            actions: "Actions",
            "delete-page-title": "Page deletion",
            "delete-page-body": "Are you sure you want to remove page ID: {itemId}?",
            description: "Description (abstract)",
            slug: "Friendly URL",
            content: "Content",
        },
        "add-page": {
            title: "Add page",
            translate: "Add translation",
        },
        "edit-page": {
            title: "Page edition",
            translate: "Add translation",
        },
        "file-repository": {
            title: "File repository",
            "add-folder": "Create folder",
            "add-file": "Upload file",
            "root-folder": "Home",
            "open-folder": "Open folder {title}",
            "file-preview": "Show {title} file preview",
            "empty-folder": "No content",
            "folder-icon": "Folder {title} icon",
            "file-icon": "File {title} icon",
            "file-info-modal-header": "File information",
            "file-title": "File title",
            "file-fileName": "File name",
            "file-extension": "File extension",
            "file-createdBy": "Author",
            "file-createdDate": "Creation date",
            "file-modifiedDate": "Modification date",
            "delete-folder-header": "Folder deletion",
            "delete-folder-body": "Are you sure you want to remove folder {title}?",
            "delete-file-header": "File deletion",
            "delete-file-body": "Are you sure you want to remove file {title}?",
            "file-deleted": "File deleted",
            "file-deleted-info": "{title} file has been deleted",
            "folder-deleted": "Folder deleted",
            "folder-deleted-info": "{title} folder has been deleted",
            "folder-editing": "Folder editing",
            "file-editing": "File editing",
        },
    },
    nav: {
        open: "Open menu",
        close: "Close menu",
    },
    languageSwitcher: {
        en: "United States of America flag",
        es: "Spanish flag",
        fr: "French flag",
        pl: "Polish flag",
        ru: "Russia flag",
        toggle: "Toggle language selector",
        zh: "China flag",
    },
    loader: {
        status: "Loading...",
    },

    // to be removed
    devTest: {
        header: "Test header en",
        btnToastErr: "Err en",
        btnToastInfo: "Info en",
        btnToastSuccess: "Success en",
        btnToastWarning: "Warning en",
        btnErrPage: "Go to error page en",
        show: "Show modal en",
        btnDisabled: "Click disabled en",
        btnGhost: "Ghost btn en",
        toastTitle: "Title en",
        toastDesc: "Description en",
        modalAccept: "Accept en",
        modalCancel: "Cancel en",
        add: "Add EN",
        remove: "Remove EN",
    },
};
