export const en = {
    general: {
        close: "Close",
        type: "Type here...",
        confirm: "Confirm",
        cancel: "Cancel",
        published: "Published",
        draft: "Draft",
        title: "Title",
        save: "Save",
        url: "URL",
        created: "Created",
        deleted: "Deleted",
        updated: "Updated",
        error: "Error occured",
        upload: "Upload",
    },
    form: {
        placeholders: {
            type: "Type here...",
            "select-one": "Select one...",
        },
        errors: {
            "invalid-email": "Invalid e-mail address",
            "invalid-url": "Invalid URL",
            "invalid-username": "Invalid username",
            "invalid-password":
                "Invalid password (at least 8 characters including a lowercase letter, an uppercase letter, number and special character)",
            "invalid-slug": "Invalid friendly URL (spaces not allowed)",
            required: "Required field",
            "passwords-not-match": "Passwords don't match",
            "required-file": "File is required",
            "invalid-relative-url": "Invalid relative URL",
        },
        actions: {
            submit: "Submit",
            "save-draft": "Save as draft",
            "submit-changes": "Submit changes",
            "save-changes-draft": "Save changes as draft",
        },
    },
    information: {
        error: {
            loading: "Oops, an error occured. Please refresh the page and if the problem persists, contact support.",
            upload: "An error occurred while adding the file - pleas try again",
            "file-invalid-type": "Invalid file type",
            "file-too-large": "Too large file - maximum file size is 10MB",
            "file-too-small": "Too small file - minimum file size is 1B",
            "too-many-files": "Too many files - single file is accepted",
        },
        success: {},
        info: {
            "no-contents": "No website content added",
            "no-pages": "No page added",
        },
    },
    pages: {
        error: {
            info: "Oops! That page does not exist.",
        },
        contents: {
            "content-title": "Title",
            "creation-date": "Creation date",
            "delete-content-body": "Are you sure you want to remove content {title} (ID: {itemId})?",
            "delete-content-title": "Content deletion",
            "delete-selected": "Delete selected",
            "modification-date": "Modification date",
            "preview-content-body": "Preview",
            "preview-content-title": "Content preview (ID: {id})",
            actions: "Actions",
            add: "Add content",
            author: "Author",
            content: "Content",
            status: "Status",
            title: "Website contents",
        },
        "manage-content": {
            "add-title": "Add content",
            preview: "Show preview",
            "edit-title": "Edit content",
        },
        page: {
            "creation-date": "Creation date",
            "delete-page-body": "Are you sure you want to remove page ID: {itemId}?",
            "delete-page-title": "Page deletion",
            "delete-selected": "Delete selected",
            "modification-date": "Modification date",
            "page-title": "Title",
            actions: "Actions",
            add: "Add page",
            author: "Author",
            content: "Content",
            description: "Description (abstract)",
            slug: "Friendly URL",
            title: "Site pages",
        },
        "manage-page": {
            "add-title": "Add page",
            "edit-title": "Edit page",
            translate: "Add translation",
        },
        "file-repository": {
            "add-file": "Upload file",
            "add-folder": "Create folder",
            "delete-file-body": "Are you sure you want to remove file {title}?",
            "delete-file-header": "File deletion",
            "delete-folder-body": "Are you sure you want to remove folder {title}?",
            "delete-folder-header": "Folder deletion",
            "empty-folder": "No content",
            "file-createdBy": "Author",
            "file-createdDate": "Creation date",
            "file-deleted-info": "{title} file has been deleted",
            "file-deleted": "File deleted",
            "file-editing": "Edit file",
            "file-extension": "File extension",
            "file-fileName": "File name",
            "file-icon": "File {title} icon",
            "file-info-modal-header": "File information",
            "file-modifiedDate": "Modification date",
            "file-preview": "Show {title} file preview",
            "file-title": "File title",
            "folder-deleted-info": "{title} folder has been deleted",
            "folder-deleted": "Folder deleted",
            "folder-editing": "Edit folder",
            "folder-icon": "Folder {title} icon",
            "open-folder": "Open folder {title}",
            "root-folder": "Root",
            title: "File repository",
            file: "File",
            upload: "<b>Drop</b> single file here or <b>click</b> to upload",
            "no-file": "File not added",
            drop: "Drop file here",
            "upload-new": "To replace an added file, add a new one by <b>drop</b> or <b>click</b>",
            "delete-folder-error": "Folder was not removed - please refresh the page and try again",
        },
        menu: {
            title: "Menu",
            add: "Add menu item",
            "add-item": "Add main menu item",
            "add-subitem": "Add child menu item",
            edit: "Edit menu item",
            "edit-on": "Edit menu",
            "edit-off": "Save menu",
            "delete-info": "Are you sure you want to remove menu item {title}?",
            save: "Are you sure you want to save the current menu structure",
            "delete-title": "Menu item deletion",
            "save-title": "Saving the menu",
            delete: "Remove menu item",
            "img-title": "Image title",
            "img-url": "Image URL",
            created: "{title} menu item has been created",
            "deleted-single": "{title} menu item has been removed",
            "deleted-multi": "{title} menu item has been removed along with its subitems",
            "updated-item": "{title} menu item has been updated",
            "update-error": "The menu structure has not been updated - please refresh the page and try again",
            "delete-error": "The menu item was not removed - please refresh the page and try again",
            "update-item-error": "The menu item was not updated - please refresh the page and try again",
            "create-error": "The menu item was not created - please refresh the page and try again",
        },
    },
    nav: {
        open: "Open menu",
        close: "Close menu",
        contents: {
            title: "Contents",
            section: {
                website: "Website contents",
                page: "Site pages",
                repository: "File repository",
                menu: "Menu",
            },
        },
        settings: {
            title: "Settings",
            section: {
                api: "API",
                catalogs: "Catalogs",
                layer: "Default layer",
                tutorial: "Tutorial tags",
                views: "Views",
                web: "Web",
            },
        },
        profile: {
            title: "Profile",
            section: {
                profile: "My profile",
                logout: "Logout",
            },
        },
    },
    languageSwitcher: {
        en: "United States of America flag",
        es: "Spanish flag",
        fr: "French flag",
        pl: "Polish flag",
        ru: "Russia flag",
        toggle: "Toggle language selector",
        zh: "China flag",
    },
    pagination: {
        page: "Page",
        show: "Show",
    },
    loader: {
        status: "Loading...",
    },

    // to be removed
    devTest: {
        header: "Test header en",
        btnToastErr: "Err en",
        btnToastInfo: "Info en",
        btnToastSuccess: "Success en",
        btnToastWarning: "Warning en",
        btnErrPage: "Go to error page en",
        show: "Show modal en",
        btnDisabled: "Click disabled en",
        btnGhost: "Ghost btn en",
        toastTitle: "Title en",
        toastDesc: "Description en",
        modalAccept: "Accept en",
        modalCancel: "Cancel en",
        add: "Add EN",
        remove: "Remove EN",
    },
};
