export const pl = {
    // to be removed
    devTest: {
        header: "Test header PL",
        btnToastErr: "Err PL",
        btnToastInfo: "Info PL",
        btnToastSuccess: "Success PL",
        btnToastWarning: "Warning PL",
        btnErrPage: "Go to error page PL",
        show: "Show modal PL",
        btnDisabled: "Click disabled PL",
        btnGhost: "Ghost btn PL",
        toastTitle: "Title PL",
        toastDesc: "Description PL",
        modalAccept: "Accept PL",
        modalCancel: "Cancel PL",
        add: "Add PL",
        remove: "Remove PL",
    },
    general: {
        title: "Tytuł",
    },
    form: {
        placeholders: {
            type: "Pisz tutaj...",
            "no-options": "Brak opcji",
        },
        errors: {
            "invalid-email": "Invalid e-mail address",
            "invalid-url": "Invalid URL",
            "invalid-username": "Invalid username",
            "invalid-password":
                "Invalid password (at least 8 characters including a lowercase letter, an uppercase letter, number and special character)",
            "invalid-slug": "Invalid friendly URL (spaces not allowed)",
            required: "Pole wymagane",
            "passwords-not-match": "Passwords don't match",
        },
    },
    pages: {
        error: {
            info: "Ups! Ta strona nie istnieje.",
        },
        contents: {
            title: "Content",
            add: "Dodaj",
            "delete-selected": "Usuń",
            "content-title": "Tytuł",
            author: "Autor",
            "creation-date": "Data utworzenia",
            "modification-date": "Data modyfikacji",
            actions: "Akcje",
            "delete-content-title": "Usuwanie contentu",
            "delete-content-body": "Czy na pewno chcesz usunąć content ID: {id}?",
            "preview-content-title": "Podgląd contentu (ID: {id})",
            "preview-content-body": "Podgląd",
            content: "Zawartość",
        },
        page: {
            title: "Strony",
            add: "Dodaj stronę",
            "delete-selected": "Usuń wybrane",
            "page-title": "Tytuł",
            author: "Autor",
            "creation-date": "Data utworzenia",
            "modification-date": "Data modyfikacji",
            actions: "Akcje",
            "delete-page-title": "Usuwanie strony",
            "delete-page-body": "Czy na pewno chcesz usunąć stronę ID: {id}?",
        },
        "add-page": {
            title: "Dodaj stronę",
            translate: "Dodaj tłumaczenie",
        },
        "edit-page": {
            title: "Edycja strony",
            translate: "Dodaj tłumaczenie",
        },
        "file-repository": {
            title: "File repository",
            "add-folder": "Dodaj folder",
            "add-file": "Dodaj plik",
            "root-folder": "Home",
            "open-folder": "Otwórz folder {title}",
            "file-preview": "Pokaż informacje o pliku {title}",
            "file-info-modal-header": "Informacje o pliku",
        },
        layer: {
            add: "Dodaj",
            edit: "Edit layer",
            name: "Name",
            visibility: "Visibility",
            visible: "Widoczna",
            invisible: "Niewidoczna",
        },
    },
    nav: {
        open: "Otwórz menu",
        close: "Zamknij menu",
    },
};
