export const pl = {
    general: {
        title: "Tytuł",
    },
    form: {
        placeholders: {
            type: "Pisz tutaj...",
            "no-options": "Brak opcji",
        },
        errors: {
            "invalid-email": "Invalid e-mail address",
            "invalid-url": "Invalid URL",
            "invalid-username": "Invalid username",
            "invalid-password":
                "Invalid password (at least 8 characters including a lowercase letter, an uppercase letter, number and special character)",
            "invalid-slug": "Invalid friendly URL (spaces not allowed)",
            required: "Pole wymagane",
            "passwords-not-match": "Passwords don't match",
        },
    },
    pages: {
        error: {
            info: "Ups! Ta strona nie istnieje.",
        },
        contents: {
            title: "Content",
            add: "Dodaj",
            "delete-selected": "Usuń",
            "content-title": "Tytuł",
            author: "Autor",
            "creation-date": "Data utworzenia",
            "modification-date": "Data modyfikacji",
            actions: "Akcje",
            "delete-content-title": "Usuwanie contentu",
            "delete-content-body": "Czy na pewno chcesz usunąć content ID: {id}?",
            "preview-content-title": "Podgląd contentu (ID: {id})",
            "preview-content-body": "Podgląd",
            content: "Zawartość",
        },
        page: {
            title: "Strony",
            add: "Dodaj stronę",
            "delete-selected": "Usuń wybrane",
            "page-title": "Tytuł",
            author: "Autor",
            "creation-date": "Data utworzenia",
            "modification-date": "Data modyfikacji",
            actions: "Akcje",
            "delete-page-title": "Usuwanie strony",
            "delete-page-body": "Czy na pewno chcesz usunąć stronę ID: {id}?",
        },
        "add-page": {
            title: "Dodaj stronę",
            translate: "Dodaj tłumaczenie",
        },
        "edit-page": {
            title: "Edycja strony",
            translate: "Dodaj tłumaczenie",
        },
        "file-repository": {
            title: "File repository",
            "add-folder": "Dodaj folder",
            "add-file": "Dodaj plik",
            "root-folder": "Home",
            "open-folder": "Otwórz folder {title}",
            "file-preview": "Pokaż informacje o pliku {title}",
            "file-info-modal-header": "Informacje o pliku",
            "delete-file-body": "Are you sure you want to remove file <b>{title}</b>?",
            "delete-file-header": "File deletion",
            "delete-folder-body": "Are you sure you want to remove folder <b>{title}</b>?",
            "delete-folder-header": "Folder deletion",
            "empty-folder": "No content",
            "file-createdBy": "Author",
            "file-createdDate": "Creation date",
            "file-deleted-info": "<b>{title}</b> file has been deleted",
            "file-deleted": "File deleted",
            "file-editing": "Edit file",
            "file-extension": "Extension",
            "file-fileName": "Name",
            "file-icon": "File {title} icon",
            "file-modifiedDate": "Modification date",
            "file-title": "Title",
            "file-link": "Link",
            "folder-deleted-info": "<b>{title}</b> folder has been deleted",
            "folder-deleted": "Folder deleted",
            "folder-editing": "Edit folder",
            "folder-icon": "Folder {title} icon",
            file: "File",
            upload: "<b>Drop</b> single file here or <b>click</b> to upload",
            "no-file": "File not added",
            drop: "Drop file here",
            "upload-new": "To replace an added file, add a new one by <b>drop</b> or <b>click</b>",
            "delete-folder-error": "Folder was not removed - please refresh the page and try again",
            copy: "Kopiuj link do schowka",
            copied: "Link skopiowany",
        },
        layer: {
            add: "Dodaj",
            edit: "Edit layer",
            name: "Name",
            visibility: "Visibility",
            visible: "Widoczna",
            invisible: "Niewidoczna",
        },
        views: {
            add: "Add view",
            "add-nested": "Add nested view",
            name: "View name",
            id: "View ID",
            parent: "Parent view name",
            default: "Default option",
            edit: "Edit view",
            "edit-nested": "Edit nested view",
            expand: "Pokaż zagnieżdzone widoki",
            "expand-all": "Pokaż wszystkie zagnieżdżone widoki",
        },
        tags: {
            type: "Typ",
            tip: "Wskazówka",
            new: "Nowość",
            show: "Widoczny",
            placement: "Położenie",
            "left-top": "left-top",
            "left-bottom": "left-bottom",
            "left-center": "left-center",
            "right-top": "right-top",
            "right-bottom": "right-bottom",
            "right-center": "right-center",
            "top-center": "top-center",
            "bottom-center": "bottom-center",
            "center-center": "center-center",
            add: "Add tutorial tag",
            edit: "Edit tutorial tag",
            "tag-added": "Tag {title} has been created",
            "tag-updated": "Tag {title} has been updated",
            "delete-tag-body": "Are you sure you want to remove tag <b>{title}</b>?",
            "delete-tag-title": "Tag deletion",
            "delete-confirmation": "Tag {title} has been deleted",
            "delete-error": "Tag {title} has not been deleted - please try again",
        },

        curatedToastsMessages: {
            statusChange: "Zmiana statusu",
            entryID: "Wpis o identyfikatorze",
            extensionID: "Rozszerzenie o identyfikatorze",
            approved: "został zatwierdzony",
            denied: "został odrzucony",
            deleted: "został usunięty",
            pending: "ma status oczekujący",
            updateResource: "Utworzono nowy zasób ze statusem aktualizuj",
            updateExtension: "Utworzono nowe rozszerzenie ze statusem aktualizuj",
        },
        recommendations: {
            add: "Dodaj nową rekomendację",
            keywordsComma: "Słowa kluczowe (oddzielone przecinkiem)",
            name: "Nazwa",
            ds: "Kod źródła danych",
            entity: "Kod jednostki",
            weight: "Priorytet",
            addButton: "Dodaj rekomendację",
            list: "Lista rekomendacji",
            keywords: "Słowa kluczowe",
            entities: "Jednostki",
            page: "Strona",
            showing: "Widoczne",
            of: "z",
            results: "wyników",
            first: "Pierwsza",
            previous: "Poprzednia",
            next: "Następna",
            last: "Ostatnia",
            modalHeader: "Zmodyfikuj rekomendację",
            addEntity: "Dodaj wpis",
            updateEntity: "Aktualizuj wpis",
            deleteEntity: "Usuń wpis",
            remove: "Usuń",
            edit: "Edytuj",
            addFormErrorInfo: "Wszystkie pola muszą być wypełnione.",
            cancelButton: "Anuluj",
        },
        workers: {
            status: "Status",
            cause: "Przyczyna",
            created: "Utworzono",
            started: "Rozpoczęto",
            ended: "Zakończono",
            updated: "Zaktualizowano",
        },
        surveyResults: {
            filter: "Filtr",
            startDate: "Data rozpoczęcia",
            endDate: "Data zakończenia",
            clearFilters: "Wyczyść filtry",
            dateTime: "Data i godzina",
            from: "Od",
            classification: "Klasyfikacja",
            fwlf: "Znaleziono to, czego szukano?",
            lookingFor: "Szukam",
            searchCriteria: "Kryteria wyszukiwania",
            visualization: "Wizualizacja",
            adequately: "Odpowiednio",
            interest: "Zainteresowanie",
            organized: "Zorganizowane",
            impression: "Wrażenie",
        },
        entryResources: {
            actionsTitle: "Działania zatwierdzone przez GEOSS",
            sync: "Synchronizuj dane zatwierdzone przez GEOSS",
            addEntity: "Dodaj wpis",
            review: "Przeglądaj przypisane wpisy",
            manage: "Zarządzaj wszystkimi wpisami",
            yourEntities: "Twoje wpisy",
            id: "ID",
            entryName: "Nazwa wpisu",
            taskType: "Typ zadania",
            startDate: "Data rozpoczęcia",
            modifiedDate: "Data modyfikacji",
            status: "Status",
            actions: "Działania",
            approve: "Zatwierdź",
            delete: "Usuń",
            deny: "Odmów",
            pending: "Oczekujący",
            edit: "Edytuj",
            editEntry: "Edytuj wpis",
            return: "Powrót do menu głównego",
            update: "Aktualizuj",
            title: "Tytuł",
            summary: "Podsumowanie",
            deleteEntry: "Usuń wpis",
            updateEntry: "Aktualizuj wpis",
            entries: "Wpisy",
            addEntityPage: {
                pageTitle: "Dodaj wpis",
                title: "Tytuł",
                logo: "Logo",
                logoTooltip: "Podaj prawidłowy adres URL obrazu.",
                summary: "Podsumowanie",
                coverage: "Zasięg",
                coverageTooltip: "Zasięg powinien być podany w następującym formacie: [-180,90],[180,-90]",
                coverageErrorMsg: "Nieprawidłowy format zasięgu. Użyj formatu z przykładu.",
                keywords: "Słowa kluczowe",
                keywordsTooltip: 'Wartości powinny być oddzielone przecinkiem, np. "ziemia,planeta"',
                tags: "Tagi",
                tagsTooltip: 'Wartości powinny być oddzielone przecinkiem, np. "ziemia,planeta"',
                updateTitle: "Edytuj wpis",
                entryContent: "Zawartość wpisu",
                additionalInfo: "Dodatkowe informacje",
                type: "Typ",
                typePlaceholder: "Wybierz typ",
                accessPolicy: "Polityka dostępu",
                accessPolicyPlaceholder: "Wybierz politykę dostępu",
                customAccessPolicy: "Niestandardowa polityka dostępu",
                customAccessPolicyPlaceholder: "Niestandardowa polityka dostępu",
                dashboardContents: "Zawartość pulpitu",
                organisation: "Organizacja",
                customOrganisation: "Niestandardowa organizacja",
                organisationPlaceholder: "Wybierz organizację",
                organisationTitlePlaceholder: "Tytuł organizacji",
                organisationEmailPlaceholder: "Email organizacji",
                organisationContactPlaceholder: "Kontakt organizacji",
                organisationContactEmailPlaceholder: "Email kontaktowy organizacji",
                source: "Źródło",
                sourcePlaceholder: "Wybierz źródło",
                customSource: "Niestandardowe źródło",
                customSourcePlaceholder: "Niestandardowe źródło",
                name: "Nazwa",
                description: "Opis",
                endpoint: "Endpoint",
                endpointPlaceholder: "Wybierz endpoint",
                endpointUrlPlaceholder: "Parametr URL endpointu",
                endpointTypePlaceholder: "Wybierz typ endpointu",
                customEndpoint: "Niestandardowy endpoint",
                protocol: "Protokół",
                protocolPlaceholder: "Wybierz protokół",
                customProtocol: "Niestandardowy protokół",
                customProtocolPlaceholder: "Niestandardowy protokół",
                linkOptions: "Linki",
                addLinkButton: "Dodaj link",
                removeOptionButton: "Usuń",
                submitButton: "Dodaj wpis",
            },
        },
        resourceExtensions: {
            manage: "Zarządzaj wszystkimi wpisami rozszerzeń",
        },
        sites: {
            errorFetchingSelectSites: "Wystąpił błąd podczas pobierania listy witryn. Proszę spróbować ponownie.",
            logoId: "ID dokumentu logo",
            id: "ID",
            image: "Obraz",
            name: "Nazwa",
            url: "URL",
            modifiedOn: "Zmodyfikowano",
            editSite: "Edytuj witrynę",
            deleteSite: "Usuń witrynę",
            delete: "Usuń",
            addSite: "Dodaj witrynę",
            addImage: "Dodaj obraz",
            confirm: "Potwierdź",
            confirmDeleteMsg: "Czy na pewno chcesz usunąć witrynę o ID:",
            siteCreatedMsg: "Witryna została utworzona.",
            siteUpdatedMsg: "Witryna została zaktualizowana.",
            siteDeletedMsg: "Witryna została usunięta.",
            siteCreationFail: "Wystąpił błąd podczas tworzenia witryny: ",
            siteDeleteFail: "Wystąpił błąd podczas usuwania witryny: ",
            siteUpdateFail: "Wystąpił błąd podczas aktualizowania witryny: ",
            imageError:
                "Bład dodawania obrazka. Upewnij się, że plik który dodajesz jest obrazkiem i nie jest plikiem GIF.",
        },
    },
    nav: {
        open: "Otwórz menu",
        close: "Zamknij menu",
        contents: {
            title: "Zawartość",
            section: {
                website: "Zawartości",
                page: "Strony",
                repository: "Repozytorium plików",
                menu: "Menu",
            },
        },
        settings: {
            title: "Ustawienia",
            section: {
                api: "API",
                catalogs: "Katalogi",
                layer: "Domyślna warstwa",
                recommendations: "Rekomendacje",
                tutorial: "Tagi samouczka",
                views: "Widoki",
                web: "Sieć",
                workers: "Workery",
            },
        },
        extensions: {
            title: "Rozszerzenia",
            section: {
                usersSurvey: "Wyniki ankiety",
                entryResources: "Zasoby",
                resourceExtensions: "Rozszerzenia",
            },
        },
        profile: {
            title: "Profil",
            section: {
                console: "Konsola",
                profile: "Mój profil",
                logout: "Wyloguj",
            },
        },
    },
};
