{{- range .Values.pvc }}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: "{{ .name }}-pv"
spec:
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - {{ .accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .volumeHandle }}
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .name }}-pvc
spec:
    accessModes:
        - {{ .accessMode }}
    storageClassName: managed-csi
    volumeName: {{ .name }}-pv
    resources:
        requests:
            storage: {{ .capacity }}
{{- end }}
